- name: copy config file from local host to remote host (relative path, ./files/)
  hosts: VM
  tasks:
    - name: copy config files
      copy:
        src: /temp/config
        dest: /temp/test/
        backup: yes
      tags: simply copy